### ISSUE TITLE
Enable flexible definition of asset name schemes from user

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#101]
I want to find a way to specify asset name schemes in onyo in a way that has at least be able to do:
- be used by `onyo new` to read a new asset file name
- `onyo set`, because it should not just be able to set contents, but also values for the name. Currently, there is no way to do this flexibly, except when assuming the name scheme will always be `<type>_<make>_<model>.<serial>` with the same reserved characters.
- `onyo mv --rename`, because currently this does not check names at all.
- `onyo fsck` should also check the name schemes
- define reserved characters for each asset template/type and for each field separately
- be compatible with future implementation of faux serials

------------

My thoughts so far were about adding a file `.onyo/validation/names.yaml` which could be easily used by `onyo new` and would be structured very similarly to the existing validation.yaml file.

```
default:
- name: <type>_<make>_<model>.<serial>
  - type:
    - reserved: _, .
  - make:
    - reserved: _, .
  - model:
    - reserved: _, .
<template name, e.g. laptop>:
  - name: <name_scheme>
```

But the problem is, I do not see how to use it with mv, fsck, set etc. All the ideas I had so far are based on "saving additional information" for each file:
- either in the asset
- in the .anchor
-  or even in an additional file

But this would directly break when changing a template name and force the user to update the names.yaml file everytime a new template would be added.

One could also track the templates and validation files with git and try to follow the information trough commits, but when then  the history would not be complete (manual rebase?), this might break the functionality again.

So long story short, I currently am still struggling to find a good mechanism to specify asset file names, that goes farther than asset creation with `onyo new`.
