### ISSUE TITLE
Validation: add key to allow only defined asset fields

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#96]
When creating certain types of assets, it might be wished, that only explicetely allowed defined fields are added to it and all other added fields not.
This might happen e.g.:

```
laptop_*
Ram:
- type: string
only_defined_keys: true
```

**Comment by aqw** [comment]
I propose another level of depth:

```
laptop_*
rules:
  - Ram:
    - type: string
only_defined_keys: true
```
