### ISSUE TITLE
Validation: allow user specific warnings/messages in error cases

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#97]
When a user creates a new asset, the validation might fail, e.g. for syntax reasons.
We might want to allow the user to add a certain message to the validation file for each field, that looks like that:
```
laptop_*
display:
   - Validate: [integer]″
   - message: screensize need to be given in format: [integer]″
```
